#apiVersion: v1
#kind: ServiceAccount
#metadata:
#  name: mysa3
#---
#priviledge SCC shouldnt never be used. Here was configured due to the nature of the images that require additional authorization. Should search a image that does not require this kind of priviledges.
#apiVersion: rbac.authorization.k8s.io/v1
#kind: ClusterRoleBinding
#metadata:
#  name: system:openshift:scc:mysqlscc
#roleRef:
#  apiGroup: rbac.authorization.k8s.io
#  kind: ClusterRole
#  name: system:openshift:scc:mysqlscc
#subjects:
#- kind: ServiceAccount
#  name: mysa3
#  namespace: {{ .Values.crb.namespace }}

#allowHostDirVolumePlugin: false
#allowHostIPC: false
#allowHostNetwork: false
#allowHostPID: false
#allowHostPorts: false
#allowPrivilegeEscalation: false
#allowPrivilegedContainer: false
#allowedCapabilities:
#- SETGID
#apiVersion: security.openshift.io/v1
#defaultAddCapabilities: null
#fsGroup:
#  type: RunAsAny
#groups:
#- system:cluster-admins
#kind: SecurityContextConstraints
#metadata:
#  annotations:
#    include.release.openshift.io/ibm-cloud-managed: "true"
#    include.release.openshift.io/self-managed-high-availability: "true"
#    include.release.openshift.io/single-node-developer: "true"
#    kubernetes.io/description: custom SCC.
#    release.openshift.io/create-only: "true"
#  name: mysqlscc
#priority: null
#readOnlyRootFilesystem: false
#runAsUser:
#  type: RunAsAny
#seLinuxContext:
#  type: MustRunAs
#supplementalGroups:
#  type: RunAsAny
#users: []
#volumes:
#- csi
#- configMap
#- downwardAPI
#- emptyDir
#- persistentVolumeClaim
#- projected
#- secret
#---
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: mysa3
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mysqlscccustomrole
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - mysqlscc
  resources:
  - securitycontextconstraints
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mysqlscccustomrole
  namespace: {{ .Values.crb.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mysqlscccustomrole
subjects:
- kind: ServiceAccount
  name: mysa3
  namespace: {{ .Values.crb.namespace }}
