apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: {{ .Values.crb.namespace }}
  name: mysqlscccustomrole
  namespace: {{ .Values.crb.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mysqlscccustomrole
subjects:
- kind: ServiceAccount
  name: mysa3
  namespace: {{ .Values.crb.namespace }}